project_id = "vvsusclhesslwgfappyd"

[functions.check-ban]
verify_jwt = false

[functions.proxy-catalyst]
verify_jwt = false

[functions.log-activity]
verify_jwt = false

[functions.check-warning]
verify_jwt = false

[functions.save-task-result]
verify_jwt = false
